version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bancoDB
      MYSQL_USER: vini
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # Persistência dos dados
    networks:
      - meu-net

networks:
  meu-net:
    driver: bridge
